name: 'ocpp'

services:

  central-system:
    build: .
    container_name: cs
    ports:
      - "9220:9220"
    network_mode: "host"
    environment:
      WEBHOOK_URL: https://cloud.ocpp-css.com/api/v1/ocpp
